# .github/workflows/release.yaml

on:
  release:
    types: [created]
    
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-20.04
    steps:
    - name: env
      run: env | sort
      
    
